### PR TITLE
Consistent code styling for sub pages

### PR DESCRIPTION
**Pull request by kiaking**

### CODE REVIEW

**Comment by kiaking** [comment]
Oh yea it is opposite sorry. I'll fix it.

**Comment by intelliriffer** [comment]
Please do check with legal, if it should be Midonet - Privacy Policy or
MidoNet.Org - Privacy policy
as one is product domain and other the Web entity.

On Wed, Jul 15, 2015 at 9:21 PM, Sandro Mathys <notifications@github.com>
wrote:

> Merged #27 <https://github.com/midonet/midonethomepage/pull/27>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/midonet/midonethomepage/pull/27#event-356611562>.
>



-- 
Regards,
Amit Talwar

**Comment by red-trela** [comment]
@intelliriffer will check, thanks

**Comment by red-trela** [comment]
Cleared by Midokura legal, it doesn't matter what the <title> says. MidoNet, midonet.org or (alsmost) anything else is okay. However, we noticed the text refers to midokura.com which is wrong - I'll fix that in a separate PR.

**Pull request merged**
